package readspec

import "testing"

// Expected values in this file were generated by calling the real Perl
// implementation (Bio::KBase::AppService::ReadSpec::_compute_sample_id and
// ::_remove_suffixes) rather than transcribed by hand.
func TestSampleIDForPair(t *testing.T) {
	cases := []struct{ read1, read2, want string }{
		{"ERR1001627_1_ptrim.fq.gz", "ERR1001627_2_ptrim.fq.gz", "ERR1001627"},
		{"/ws/user/home/SRR12345_1.fastq.gz", "/ws/user/home/SRR12345_2.fastq.gz", "SRR12345"},
		{"sample_R1.fq", "sample_R2.fq", "sample"},
		{"reads_1.fastq", "reads_2.fastq", "reads"},
		{"ABCD_1.fq", "ABCD_2.fq", "ABCD"},
		// Common prefix shorter than 5 -> fall back to read1 single-file rule.
		{"a1.fq", "a2.fq", "a1"},
		{"x_1.fq.gz", "y_2.fq.gz", "x_1"},
		// Identical names: Perl's unbounded loop spins here; we stop at the
		// end of the string and use the whole basename.
		{"identical.fq", "identical.fq", "identical.fq"},
	}
	for _, c := range cases {
		if got := SampleIDForPair(c.read1, c.read2); got != c.want {
			t.Errorf("SampleIDForPair(%q,%q) = %q, want %q", c.read1, c.read2, got, c.want)
		}
	}
}

func TestSampleIDForFile(t *testing.T) {
	cases := []struct{ in, want string }{
		{"ERR1001627_1_ptrim.fq.gz", "ERR1001627_1_ptrim"},
		{"/ws/u/reads.fastq", "reads"},
		{"single_a.fq", "single"},
		{"noext", "noext"},
		{"x.tar.gz", "x"},
		{"UPPER_A.FQ", "UPPER"},
	}
	for _, c := range cases {
		if got := SampleIDForFile(c.in); got != c.want {
			t.Errorf("SampleIDForFile(%q) = %q, want %q", c.in, got, c.want)
		}
	}
}

func TestSRRKeyAndShape(t *testing.T) {
	cases := []struct {
		name   string
		opts   Options
		key    string
		object bool
	}{
		// Perl: ReadSpec->new($uploader)
		{"Variation", Options{}, "srr_ids", false},
		// Perl: simple => 1, single => 1
		{"MetagenomeBinning", Options{Simple: true}, "srr_ids", false},
		// Perl: assembling => 1
		{"SARS2Assembly", Options{}, "srr_ids", false},
		// Perl: rnaseq => 1
		{"RNASeq", Options{RNASeq: true}, "srr_libs", true},
		// Perl: simple => 1, samples => 1
		{"TaxonomicClassification", Options{Simple: true, Samples: true}, "srr_libs", true},
		// Perl: samples => 1, analysis => 1
		{"SARS2Wastewater", Options{Samples: true, Analysis: true}, "srr_libs", true},
		// srrAlt alone gives object entries but leaves the default key.
		{"srrAlt only", Options{Simple: true, SRRAlt: true}, "srr_ids", true},
		// Perl: simple => 1, srrAlt => 1, then $reader->{srr_label} = 'srr_libs'
		// (p3-submit-fastqutils.pl:92).
		{"FastqUtils", Options{Simple: true, SRRAlt: true, SRRKeyOverride: "srr_libs"}, "srr_libs", true},
	}
	for _, c := range cases {
		if got := c.opts.SRRKey(); got != c.key {
			t.Errorf("%s: SRRKey() = %q, want %q", c.name, got, c.key)
		}
		if got := c.opts.SRRIsObject(); got != c.object {
			t.Errorf("%s: SRRIsObject() = %v, want %v", c.name, got, c.object)
		}
	}
}

func TestLibBuilders(t *testing.T) {
	tax := Options{Simple: true, Samples: true}

	lib := tax.PairedLib("/ws/ERR1001627_1_ptrim.fq.gz", "/ws/ERR1001627_2_ptrim.fq.gz")
	if lib["sample_id"] != "ERR1001627" {
		t.Errorf("PairedLib sample_id = %v, want ERR1001627", lib["sample_id"])
	}
	if lib["read1"] == nil || lib["read2"] == nil {
		t.Error("PairedLib must retain read1/read2")
	}

	single := tax.SingleLib("/ws/ERR999_a.fq")
	if single["sample_id"] != "ERR999" {
		t.Errorf("SingleLib sample_id = %v, want ERR999", single["sample_id"])
	}

	srr := tax.SRREntry("SRR12345")
	if srr["srr_accession"] != "SRR12345" || srr["sample_id"] != "SRR12345" {
		t.Errorf("SRREntry = %v, want accession and sample_id SRR12345", srr)
	}

	// Without Samples, no sample_id is added anywhere.
	plain := Options{RNASeq: true}
	if _, ok := plain.PairedLib("a_1.fq", "a_2.fq")["sample_id"]; ok {
		t.Error("PairedLib must not set sample_id when Samples is false")
	}
	if _, ok := plain.SRREntry("SRR1")["sample_id"]; ok {
		t.Error("SRREntry must not set sample_id when Samples is false")
	}
}
